[build]
  # Diretório base para rodar os comandos
  base = "frontend"
  # Comando para construir o site
  command = "npm run build"
  # Pasta que será publicada após o build
  publish = "frontend/build"

[[redirects]]
  # Para qualquer rota que o navegador pedir...
  from = "/*"
  # ...sirva o arquivo index.html...
  to = "/index.html"
  # ...e diga que a requisição foi um sucesso.
  status = 200