# Generated by Django 5.2.4 on 2025-07-03 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cirurgia', models.DateField(blank=True, null=True)),
                ('peso_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('meta_peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
