# Generated by Django 5.2.4 on 2025-07-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='altura_cm',
            field=models.PositiveIntegerField(blank=True, help_text='Altura em centímetros', null=True),
        ),
    ]
