# Generated by Django 5.2.4 on 2025-07-05 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0002_perfil_altura_cm'),
        ('perfis', '0003_auto_20250705_1842'),
    ]

    operations = [
    ]
