# Generated by Django 5.2.4 on 2025-07-03 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateField()),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso em kg (ex: 85.5)', max_digits=5, null=True)),
                ('agua_ml', models.PositiveIntegerField(blank=True, help_text='Quantidade de água consumida em ml', null=True)),
                ('vitaminas_tomadas', models.BooleanField(default=False, help_text='Marque se tomou as vitaminas')),
                ('observacoes', models.TextField(blank=True, help_text='Anote como se sentiu, o que comeu, etc.', max_length=500)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_diarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_registro'],
                'unique_together': {('usuario', 'data_registro')},
            },
        ),
    ]
