# Generated by Django 5.2.4 on 2025-07-05 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cafe_da_manha', 'Café da Manhã'), ('lanche_da_manha', 'Lanche da Manhã'), ('almoco', 'Almoço'), ('lanche_da_tarde', 'Lanche da Tarde'), ('jantar', 'Jantar'), ('ceia', 'Ceia'), ('outra', 'Outra')], default='outra', max_length=20)),
                ('descricao', models.TextField(help_text='Descreva o que você comeu e bebeu.', max_length=500)),
                ('horario', models.TimeField()),
                ('registro_diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refeicoes', to='acompanhamento.registrodiario')),
            ],
        ),
    ]
