# Generated by Django 5.2.4 on 2025-07-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0002_refeicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do alimento, ex: Maçã Fuji', max_length=100)),
                ('marca', models.CharField(blank=True, help_text='Marca do produto, se aplicável', max_length=100, null=True)),
                ('porcao_gramas', models.PositiveIntegerField(default=100, help_text='A porção base em gramas para os valores nutricionais (ex: 100)')),
                ('calorias', models.DecimalField(decimal_places=2, help_text='Kcal por porção', max_digits=7)),
                ('proteinas', models.DecimalField(decimal_places=2, default=0, help_text='Gramas de proteína por porção', max_digits=7)),
                ('carboidratos', models.DecimalField(decimal_places=2, default=0, help_text='Gramas de carboidratos por porção', max_digits=7)),
                ('gorduras', models.DecimalField(decimal_places=2, default=0, help_text='Gramas de gordura por porção', max_digits=7)),
            ],
        ),
    ]
