# Generated by Django 5.2.4 on 2025-07-06 01:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0004_alter_registrodiario_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodiario',
            name='data_registro',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='registrodiario',
            unique_together={('usuario', 'data_registro')},
        ),
    ]
