# Generated by Django 5.2.4 on 2025-07-07 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0005_alter_registrodiario_data_registro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_hora', models.DateTimeField()),
                ('local', models.CharField(blank=True, max_length=200, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compromissos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_hora'],
            },
        ),
    ]
